global using System.Collections.Immutable;
global using KLP.GUI.DataContracts;
global using KLP.GUI.DataContracts.Serialization;
global using KLP.GUI.Models;
global using KLP.GUI.Services.Caching;
global using KLP.GUI.Services.Endpoints;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
